// <auto-generated />
using LessaShoes.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LessaShoes.Persistance.Migrations
{
    [DbContext(typeof(LessaShoesContext))]
    [Migration("20210627164331_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("LessaShoes.Domain.tenis", b =>
                {
                    b.Property<int>("tenisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("imagemURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("nomeTenis")
                        .HasColumnType("TEXT");

                    b.Property<int>("qtdTenis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tamanho")
                        .HasColumnType("INTEGER");

                    b.HasKey("tenisID");

                    b.ToTable("Tenis");
                });

            modelBuilder.Entity("LessaShoes.Domain.usuario", b =>
                {
                    b.Property<int>("usuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cargo")
                        .HasColumnType("TEXT");

                    b.Property<int>("idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imagemURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("nomeUsuario")
                        .HasColumnType("TEXT");

                    b.HasKey("usuarioID");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
