// <auto-generated />
using LessaShoes.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LessaShoes.Persistance.Migrations
{
    [DbContext(typeof(LessaShoesContext))]
    partial class LessaShoesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("LessaShoes.Domain.tenis", b =>
                {
                    b.Property<int>("tenisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("disponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeTenis")
                        .HasColumnType("TEXT");

                    b.Property<int>("qtdTenis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tamanho")
                        .HasColumnType("INTEGER");

                    b.HasKey("tenisID");

                    b.ToTable("Tenis");
                });

            modelBuilder.Entity("LessaShoes.Domain.usuario", b =>
                {
                    b.Property<int>("usuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeUsuario")
                        .HasColumnType("TEXT");

                    b.HasKey("usuarioID");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
